name: build
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 3 * * 0"
jobs:
  build:
    name: build container image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: apache-openidc
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
      # - name: Remove untagged images
      #   uses: actions/github-script@v6
      #   with:
      #     github-token: ${{ secrets.GHCR_DELETE_TOKEN }}
      #     script: |
      #       const response = await github.request("GET /user/packages/container/${{ env.IMAGE_NAME }}/versions");
      #       for(version of response.data) {
      #           if (version.metadata.container.tags.length == 0) {
      #               const deleteResponse = await github.request("DELETE /user/packages/container/${{ env.IMAGE_NAME }}/versions/" + version.id, { });
      #               console.log("[status] " + deleteResponse.status);
      #               console.log("Deleted version " + version.id);
      #           }
      #       }
