name: build
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 3 * * 0"
jobs:
  build:
    name: build container image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: apache-openidc
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Build image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest .
      - name: Push to GHCR
        run: |
          docker login --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} ghcr.io
          docker push ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          docker logout ghcr.io
      - name: Remove untagged images
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GHCR_DELETE_TOKEN }}
          script: |
            const response = await github.request("GET /user/packages/container/${{ env.IMAGE_NAME }}/versions");
            for(version of response.data) {
                if (version.metadata.container.tags.length == 0) {
                    const deleteResponse = await github.request("DELETE /user/packages/container/${{ env.IMAGE_NAME }}/versions/" + version.id, { });
                    console.log("[status] " + deleteResponse.status);
                    console.log("Deleted version " + version.id);
                }
            }
